services:
  bowling_api:
    build:
      context: .
      dockerfile: bowling_api/Dockerfile
    container_name: bowling_api
    networks:
      - proxy
    expose:
      - "3000"
    restart: unless-stopped

  bowling_ui:
    build:
      context: ./bowling_ui
    container_name: bowling_ui
    networks:
      - proxy
    #ports:
      #- "8085:80"
    depends_on:
      - bowling_api
    restart: unless-stopped

networks:
  proxy:
    external: true
