services:
  bowling_api:
    image: ghcr.io/kabaize/bowling-game-scorer-api
    container_name: bowling_api
    networks:
      - proxy
    expose:
      - "3000"
    restart: unless-stopped

  bowling_ui:
    image: ghcr.io/kabaize/bowling-game-scorer-ui
    container_name: bowling_ui
    networks:
      - proxy
    depends_on:
      - bowling_api
    restart: unless-stopped

networks:
  proxy:
    external: true
