services:
  bowling_api:
    image: ghcr.io/kabaize/bowling-game-scorer-api:latest
    container_name: bowling_api
    networks:
      - bowling-game-scorer-net
    restart: unless-stopped

  bowling_ui:
    image: ghcr.io/kabaize/bowling-game-scorer-ui:latest
    container_name: bowling_ui
    networks:
      - bowling-game-scorer-net
    ports:
      - "8085:80"
    depends_on:
      - bowling_api
    restart: unless-stopped

networks:
  bowling-game-scorer-net:
